# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x03\x61pi\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1b\n\x0cTradeRequest\x12\x0b\n\x03sym\x18\x01 \x01(\t\"+\n\rTradeResponse\x12\x1a\n\x06trades\x18\x01 \x03(\x0b\x32\n.api.Trade\"Z\n\x05Trade\x12(\n\x04time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0b\n\x03sym\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x01\x12\x0b\n\x03qty\x18\x04 \x01(\x03\x32\x42\n\x0b\x44\x61taService\x12\x33\n\x08GetTrade\x12\x11.api.TradeRequest\x1a\x12.api.TradeResponse\"\x00\x42\x07Z\x05./apib\x06proto3')



_TRADEREQUEST = DESCRIPTOR.message_types_by_name['TradeRequest']
_TRADERESPONSE = DESCRIPTOR.message_types_by_name['TradeResponse']
_TRADE = DESCRIPTOR.message_types_by_name['Trade']
TradeRequest = _reflection.GeneratedProtocolMessageType('TradeRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRADEREQUEST,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:api.TradeRequest)
  })
_sym_db.RegisterMessage(TradeRequest)

TradeResponse = _reflection.GeneratedProtocolMessageType('TradeResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRADERESPONSE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:api.TradeResponse)
  })
_sym_db.RegisterMessage(TradeResponse)

Trade = _reflection.GeneratedProtocolMessageType('Trade', (_message.Message,), {
  'DESCRIPTOR' : _TRADE,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:api.Trade)
  })
_sym_db.RegisterMessage(Trade)

_DATASERVICE = DESCRIPTOR.services_by_name['DataService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\005./api'
  _TRADEREQUEST._serialized_start=52
  _TRADEREQUEST._serialized_end=79
  _TRADERESPONSE._serialized_start=81
  _TRADERESPONSE._serialized_end=124
  _TRADE._serialized_start=126
  _TRADE._serialized_end=216
  _DATASERVICE._serialized_start=218
  _DATASERVICE._serialized_end=284
# @@protoc_insertion_point(module_scope)
